baseURL = 'https://antscoding.antoss.org/'
languageCode = 'en-us'
title = 'antsCoding'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 2

[caches]
  [caches.images]
    dir = ':cacheDir/images'
